[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
tee = []
amd-sev = [ "tee" ]
amd-snp = [ "tee" ]

[dependencies]
libc = ">=0.2.39"
vm-memory = { version = "0.8.0", features = ["backend-mmap"] }

arch_gen = { path = "../arch_gen" }
utils = { path = "../utils" }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.4"

[dev-dependencies]
utils = { path = "../utils" }
