[package]
name = "libkrun"
version = "0.1.0"
authors = ["Sergio Lopez <slp@redhat.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
libc = ">=0.2.39"

logger = { path = "../logger" }
polly = { path = "../polly" }
utils = { path = "../utils" }
vmm = { path = "../vmm" }

[build-dependencies]
cc = "1.0"

[lib]
name = "krun"
crate-type = ["cdylib"]