[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.4"
libc = ">=0.2.39"

arch = { path = "../arch" }
devices = { path = "../devices" }
kernel = { path = "../kernel" }
logger = { path = "../logger" }
vm-memory = { path = "../vm-memory", features = ["backend-mmap"] }
utils = { path = "../utils"}
polly = { path = "../polly" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
cpuid = { path = "../cpuid" }

[dev-dependencies]
vmm-sys-util = ">=0.4.0"
